### ISSUE TITLE
[UI] Analytics has less left margin on the Analytics Page only

### ISSUE THREAD

**Issue by andrewmfraser** [FraserCoyle/sermon-manager-issues#157]
Analytics Page:
<img width="846" alt="screenshot 2016-04-24 09 09 17" src="https://cloud.githubusercontent.com/assets/231299/14766312/59b60dfe-09fc-11e6-9025-4d0a7793d260.png">
Sermons Page:
<img width="855" alt="screenshot 2016-04-24 09 09 27" src="https://cloud.githubusercontent.com/assets/231299/14766313/5b1014d8-09fc-11e6-87b0-9bb4d52c82eb.png">

**Comment by jonahm** [comment]
Should be fixed now?

**Comment by andrewmfraser** [comment]
Still not fixed - the active menu item is a different width which causes "jumping" when switching between pages

**Comment by jonahm** [comment]
<img src="https://i.imgur.com/pBsNIyC.png">
